[package]
name = "redmine-tui-draft"
version = "0.1.0"
description = "draft app for redmine-tui"
authors = ["ano333333 <ano333333github@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
directories = "6.0.0"
lazy_static = "1.5.0"
ratatui = "0.30.0"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
